name: Deploy Discord Bot to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker build -t pointstick-bot .

    - name: Save image to tar
      run: docker save pointstick-bot -o pointstick-bot.tar

    - name: Upload and deploy on VPS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          # Create target folder if needed
          mkdir -p ${{ secrets.VPS_DEPLOY_PATH }}
          
          # Accept tar from stdin and write it to file
          cat > ${{ secrets.VPS_DEPLOY_PATH }}/pointstick-bot.tar

          # Move to path and run deployment
          cd ${{ secrets.VPS_DEPLOY_PATH }}
          docker compose down
          docker load < pointstick-bot.tar
          docker compose up -d
      env:
        TAR_FILE: pointstick-bot.tar
      # 👇 Redirect local file to remote input
      shell: bash
      run: |
        cat $TAR_FILE | ssh -i ${{ secrets.VPS_SSH_KEY }} -o StrictHostKeyChecking=no ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} 'bash -s'

    - name: Clean up local tar
      run: rm pointstick-bot.tar
